### ISSUE TITLE
Driver Connects but No Data are Published

### ISSUE THREAD

**Issue by JWhitleyWork** [polyexplore/ROS2_Driver#1]
The following are all of the relevant outputs from the `polyx_talker_node` from my vehicle launch file:

```
[INFO] [polyx_node_talker-6]: process started with pid [977336]
[polyx_node_talker-6] [INFO] [1643845588.805272696] [gnss.polyexplore_node]: ethernet is On
[polyx_node_talker-6] [INFO] [1643845588.805398377] [gnss.polyexplore_node]: eth_server = 192.168.0.120
[polyx_node_talker-6] [INFO] [1643845588.805419497] [gnss.polyexplore_node]: eth_port = 8888
[polyx_node_talker-6] [INFO] [1643845588.805993300] [gnss.polyexplore_node]: connectEthernet Success!
[polyx_node_talker-6] 
[polyx_node_talker-6] [INFO] [1643845588.806407303] [gnss.polyexplore_node]: serial port=
[polyx_node_talker-6] [INFO] [1643845588.806439103] [gnss.polyexplore_node]: serial baud=0
[polyx_node_talker-6] [INFO] [1643845588.806455183] [gnss.polyexplore_node]: output msgs=-1
[polyx_node_talker-6] [INFO] [1643845588.806474823] [gnss.polyexplore_node]: wheel speed=/gnss/events/WheelSpeed
[polyx_node_talker-6] [INFO] [1643845588.806490303] [gnss.polyexplore_node]: static heading=/gnss/events/StaticHeading
[polyx_node_talker-6] [INFO] [1643845588.806505543] [gnss.polyexplore_node]: static geopose=/gnss/events/StaticGeoPose
[polyx_node_talker-6] [INFO] [1643845588.815059190] [gnss.polyexplore_node]: Talker Initialized!
```

And this is the param file that I'm using:

```
/**:
  ros__parameters:
    use_sim_time: False
    eth_enable: True
    eth_server: 192.168.0.120
    eth_port: "8888"
    polyx_wheelspeed:   "/gnss/events/WheelSpeed"
    polyx_staticheading: "/gnss/events/StaticHeading"
    polyx_staticgeopose: "/gnss/events/StaticGeoPose"
    polyx_output: 0xFFFFFFFF
```

Everything appears to be connecting correctly but echoing *any* of the topics shows no data being produced. Please let me know if I'm doing something wrong.
